;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/parse/components/wxParseImg"],{7722:function(e,t,n){"use strict";var r;n.d(t,"b",(function(){return a})),n.d(t,"c",(function(){return i})),n.d(t,"a",(function(){return r}));var a=function(){var e=this,t=e.$createElement;e._self._c},i=[]},"90c6":function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var r=a(n("a34a"));function a(e){return e&&e.__esModule?e:{default:e}}function i(e,t,n,r,a,i,u){try{var c=e[i](u),o=c.value}catch(f){return void n(f)}c.done?t(o):Promise.resolve(o).then(r,a)}function u(e){return function(){var t=this,n=arguments;return new Promise((function(r,a){var u=e.apply(t,n);function c(e){i(u,r,a,c,o,"next",e)}function o(e){i(u,r,a,c,o,"throw",e)}c(void 0)}))}}var c={name:"wxParseImg",data:function(){return{newStyleStr:"",preview:!0}},inject:["parseWidth","parseGetWidth"],mounted:function(){},props:{node:{type:Object,default:function(){return{}}}},methods:{wxParseImgTap:function(e){if(this.preview){var t=e.currentTarget.dataset.src;if(t){var n=this.$parent;while(!n.preview||"function"!==typeof n.preview)n=n.$parent;n.preview(t,e)}}},wxParseImgLoad:function(e){var t=this;return u(r.default.mark((function n(){var a,i,u,c,o,f,s,d,p,l,h,v;return r.default.wrap((function(n){while(1)switch(n.prev=n.next){case 0:if(a=e.currentTarget.dataset.src,a){n.next=3;break}return n.abrupt("return");case 3:return i=e.mp.detail,u=i.width,c=i.height,n.next=6,t.wxAutoImageCal(u,c);case 6:o=n.sent,f=o.imageheight,s=o.imageWidth,d=t.node.attr,p=d.padding,l=d.mode,h=t.node.styleStr,v="widthFix"===l?"":"height: ".concat(f,"px;"),s?h||(t.newStyleStr="".concat(h,"; ").concat(v,"; width: ").concat(s,"px; padding: 0 ").concat(+p,"px;")):h||(t.newStyleStr="".concat(h,"; ").concat(v,"; width: 100%; padding: 0 ").concat(+p,"px;"));case 12:case"end":return n.stop()}}),n)})))()},wxAutoImageCal:function(e,t){var n=this;return u(r.default.mark((function a(){var i,u,c,o;return r.default.wrap((function(r){while(1)switch(r.prev=r.next){case 0:if(i=n.parseWidth.value,u={},i){r.next=5;break}return r.next=5,n.parseGetWidth().then((function(e){i=e}));case 5:if(e<60||t<60){c=n.node.attr.src,o=n.$parent;while(!o.preview||"function"!==typeof o.preview)o=o.$parent;o.removeImageUrl(c),n.preview=!1}return e>i?(u.imageWidth=i,u.imageheight=i*(t/e)):(u.imageWidth=e,u.imageheight=t),r.abrupt("return",u);case 8:case"end":return r.stop()}}),a)})))()}}};t.default=c},9312:function(e,t,n){"use strict";n.r(t);var r=n("90c6"),a=n.n(r);for(var i in r)"default"!==i&&function(e){n.d(t,e,(function(){return r[e]}))}(i);t["default"]=a.a},bb2f:function(e,t,n){"use strict";n.r(t);var r=n("7722"),a=n("9312");for(var i in a)"default"!==i&&function(e){n.d(t,e,(function(){return a[e]}))}(i);var u,c=n("f0c5"),o=Object(c["a"])(a["default"],r["b"],r["c"],!1,null,null,null,!1,r["a"],u);t["default"]=o.exports}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/parse/components/wxParseImg-create-component',
    {
        'components/parse/components/wxParseImg-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("bb2f"))
        })
    },
    [['components/parse/components/wxParseImg-create-component']]
]);
