;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/wxxieyi/wxxieyi"],{6485:function(t,n,e){},7261:function(t,n,e){"use strict";e.r(n);var i=e("d31a"),a=e("e97c");for(var o in a)"default"!==o&&function(t){e.d(n,t,(function(){return a[t]}))}(o);e("a6cb");var r,c=e("f0c5"),u=Object(c["a"])(a["default"],i["b"],i["c"],!1,null,null,null,!1,i["a"],r);n["default"]=u.exports},a6cb:function(t,n,e){"use strict";var i=e("6485"),a=e.n(i);a.a},d31a:function(t,n,e){"use strict";var i;e.d(n,"b",(function(){return a})),e.d(n,"c",(function(){return o})),e.d(n,"a",(function(){return i}));var a=function(){var t=this,n=t.$createElement,e=(t._self._c,t.needAuthorization?t.t("color1"):null),i=t.needAuthorization&&void 0!=e?t.t("color1"):null;t.$mp.data=Object.assign({},{$root:{m0:e,m1:i}})},o=[]},d642:function(t,n,e){"use strict";(function(t,e){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var i=getApp(),a={data:function(){return{needAuthorization:!1,privacyContractName:"",resolvePrivacyAuthorization:""}},mounted:function(){},methods:{getPrivacySetting:function(){var n=this;t.getPrivacySetting({success:function(t){t.needAuthorization&&(e.hideLoading(),n.needAuthorization=t.needAuthorization,n.privacyContractName=t.privacyContractName)},fail:function(t){i.error(t)}})},handleAgreePrivacyAuthorization:function(){this.needAuthorization=!1,this.resolvePrivacyAuthorization({buttonId:"agree-btn",event:"agree"})},handleOpenPrivacyContract:function(){t.openPrivacyContract()}}};n.default=a}).call(this,e("c11b")["default"],e("c11b")["default"])},e97c:function(t,n,e){"use strict";e.r(n);var i=e("d642"),a=e.n(i);for(var o in i)"default"!==o&&function(t){e.d(n,t,(function(){return i[t]}))}(o);n["default"]=a.a}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/wxxieyi/wxxieyi-create-component',
    {
        'components/wxxieyi/wxxieyi-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("7261"))
        })
    },
    [['components/wxxieyi/wxxieyi-create-component']]
]);
