<?php
/**
 * 点大商城（www.diandashop.com） - 微信公众号小程序商城系统!
 * Copyright © 2020 山东点大网络科技有限公司 保留所有权利
 * =========================================================
 * 版本：V2
 * 授权主体：乐扬科技有限公司
 * 授权域名：266.xfdianda.com
 * 授权码：OStjSGnXAQjzHsXwkXnCRSZcd
 * ----------------------------------------------
 * 您只能在商业授权范围内使用，不可二次转售、分发、分享、传播
 * 任何企业和个人不得对代码以任何目的任何形式的再发布
 * =========================================================
 */

// +----------------------------------------------------------------------
// | 优惠券
// +----------------------------------------------------------------------
namespace app\controller;
use think\facade\View;
use think\facade\Db;

class Coupon extends Common
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        }

    //列表
	public function index(){
		if(request()->isAjax()){
			$page = input('param.page');
			$limit = input('param.limit');
			$time = time();
			if(input('param.field') && input('param.order')){
				$order = input('param.field').' '.input('param.order');
			}else{
				//$order = 'id desc';
				$order = Db::raw("if(UNIX_TIMESTAMP(endtime) > {$time},1,0) desc,sort desc");
			}
			$where = array();
			$where[] = ['aid','=',aid];
            if(false){}else{
                $where[] = ['bid','=',bid];
            }
			if(input('param.type') != 'all')
                $where[] = ['type','<>',5];//餐饮类排除
			    $where[] = ['type','<>',6];//酒店类排除
                if(input('param.name')) $where[] = ['name','like','%'.input('param.name').'%'];
			$count = 0 + Db::name('coupon')->where($where)->count();
			$data = Db::name('coupon')->where($where)->page($page,$limit)->order($order)->select()->toArray();
			foreach($data as $k=>$v){
                $data[$k]['type_txt'] = \app\common\Coupon::getCouponTypeTxt($v['type']);
				if(strtotime($v['starttime']) > time()){
					$data[$k]['status'] = '<button class="layui-btn layui-btn-sm" style="background-color:#888">未开始</button>';
				}elseif(strtotime($v['endtime']) < time()){
					$data[$k]['status'] = '<button class="layui-btn layui-btn-sm layui-btn-disabled">已结束</button>';
				}else{
					$data[$k]['status'] = '<button class="layui-btn layui-btn-sm" style="background-color:#5FB878">进行中</button>';
				}
                //增加计算已使用的数量
                $data[$k]['used_count']  = 0 + Db::name('coupon_record')->where(['couponid'=>$v['id'],'status'=>1])->count();
                //商家
                if($v['bid']>0){
                    $data[$k]['bname'] = Db::name('business')->where('aid', aid)->where('id', $v['bid'])->value('name');
                }else{
                    $data[$k]['bname'] = '平台';
                }
			}
			return json(['code'=>0,'msg'=>'查询成功','count'=>$count,'data'=>$data]);
		}

        View::assign('send_coupon',getcustom('business_member_send_coupon'));
		return View::fetch();
	}

	//编辑
	public function edit(){
		if(input('param.id')){
			$info = Db::name('coupon')->where('aid',aid)->where('bid',bid)->where('id',input('param.id/d'))->find();
		}else{
			$info = array('id'=>'','perlimit'=>1,'yxqtype'=>1,'yxqtime'=>date('Y-m-d 00:00:00').' ~ '.date('Y-m-d 00:00:00',time()+7*86400),'starttime'=>date('Y-m-d 00:00:00'),'endtime'=>date('Y-m-d 00:00:00',time()+7*86400),'gettj'=>'-1','showtj'=>'-1','usetj'=>'-1','sort'=>0,'fwtype'=>0,'limit_count' => 1);
		}
		$info['gettj'] = explode(',',$info['gettj']);
		$info['showtj'] = explode(',',$info['showtj']);
		$info['usetj'] = explode(',',$info['usetj']);
        $info['buypro_give_num'] = explode(',',$info['buypro_give_num']);

    	$info['buyyuyuepro_give_num'] = $info && !empty($info['buyyuyuepro_give_num'])?explode(',',$info['buyyuyuepro_give_num']):'';
    	$yuyue_products2 = array();
		if($info && !empty($info['buyyuyueproids'])){
			$yuyue_products2 = Db::name('yuyue_product')->where('id','in',$info['buyyuyueproids'])->where('aid',aid)->where('bid',bid)->order('sort desc,id')->select()->toArray();
		}
		View::assign('yuyue_products2',$yuyue_products2);
		View::assign('info',$info);

        $default_cid = Db::name('member_level_category')->where('aid',aid)->where('isdefault', 1)->value('id');
        $default_cid = $default_cid ? $default_cid : 0;
        $memberlevel = Db::name('member_level')->where('aid',aid)->where('cid', $default_cid)->order('sort,id')->select()->toArray();
		View::assign('memberlevel',$memberlevel);

		$categorydata = array();
		if($info && $info['categoryids']){
			$categorydata = Db::name('shop_category')->where('aid',aid)->where('id','in',$info['categoryids'])->order('sort desc,id')->select()->toArray();
		}
		View::assign('categorydata',$categorydata);
		$categorydata2 = array();
		if($info && $info['categoryids2']){
			$categorydata2 = Db::name('shop_category2')->where('aid',aid)->where('bid',bid)->where('id','in',$info['categoryids2'])->order('sort desc,id')->select()->toArray();
		}
		View::assign('categorydata2',$categorydata2);
		$productdata = array();
		if($info && $info['productids']){
			$productdata = Db::name('shop_product')->where('aid',aid)->where('bid',bid)->where('id','in',$info['productids'])->order('sort desc,id')->select()->toArray();
		}
		$productdata2 = array();
		if($info && $info['buyproids']){
			$productdata2 = Db::name('shop_product')->where('aid',aid)->where('bid',bid)->where('id','in',$info['buyproids'])->order('sort desc,id')->select()->toArray();
		}
        $restaurant_product = array();
        if($info && $info['restaurant_productids']){
            $restaurant_product = Db::name('restaurant_product')->where('aid',aid)->where('bid',bid)->where('id','in',$info['restaurant_productids'])->order('sort desc,id')->select()->toArray();
        }
        $restaurant_product2 = array();
        if($info && $info['buy_restaurant_product_ids']){
            $restaurant_product2 = Db::name('restaurant_product')->where('aid',aid)->where('bid',bid)->where('id','in',$info['buy_restaurant_product_ids'])->order('sort desc,id')->select()->toArray();
        }
        $yuyue_product = array();
        if($info && $info['yuyue_productids']){
            $yuyue_product = Db::name('yuyue_product')->where('aid',aid)->where('bid',bid)->where('id','in',$info['yuyue_productids'])->order('sort desc,id')->select()->toArray();
        }
        View::assign('productdata',$productdata);
		View::assign('productdata2',$productdata2);
        View::assign('restaurant_product',$restaurant_product);
        View::assign('restaurant_product2',$restaurant_product2);
        View::assign('yuyue_product',$yuyue_product);
        $config = include(ROOT_PATH.'/config.php');
        if(isset($config['restaurant'])) {
            View::assign('restaurant',true);
        }
        if($this->auth_data == 'all' || in_array('YuyueList/*',$this->auth_data)){
            $auth['yuyue'] = true;
        }
        if($this->auth_data == 'all' || in_array('BusinessMaidan/*',$this->auth_data)){
            $auth['maidan'] = true;
        }
        if($this->auth_data == 'all' || in_array('Cashier/*',$this->auth_data)){
            $auth['cashier'] = true;
        }
        View::assign('auth',$auth);

		View::assign('uid',$this->uid);
        $product_givetongzheng = getcustom('product_givetongzheng')?:0;
        View::assign('product_givetongzheng',$product_givetongzheng);
        View::assign('bid',bid);
        return View::fetch();
	}
	//保存
	public function save(){
		$info = input('post.info/a');
		$info['gettj'] = implode(',',$info['gettj']);
		$info['showtj'] = implode(',',$info['showtj']);
		if($info['paygive_scene']){
			$info['paygive_scene'] = implode(',',$info['paygive_scene']);
		}else{
			$info['paygive_scene'] = '';
		}
		//优惠券有效期
        if($info['yxqtype'] == 2) {
            $info['yxqdate'] = input('post.yxqdate2');
        }
        if($info['yxqtype'] == 3) {
            $info['yxqdate'] = input('post.yxqdate3');
        }

		$info['buypro_give_num'] = implode(',',$info['buypro_give_num']);
		if(!$info['buypro_give_num']) $info['buypro_give_num'] = '1';

		if($info['buyyuyuepro_give_num']){
            $info['buyyuyuepro_give_num'] = implode(',',$info['buyyuyuepro_give_num']);
        }else{
            $info['buyyuyuepro_give_num'] = '1';
        }
        if($info['id']){
			Db::name('coupon')->where('aid',aid)->where('bid',bid)->where('id',$info['id'])->update($info);
			\app\common\System::plog('编辑'.t('优惠券').$info['id']);
		}else{
			$info['aid'] = aid;
			$info['bid'] = bid;
			$info['createtime'] = time();
			if($info['type'] != 3)
			    $info['limit_count'] = 1;
			$id = Db::name('coupon')->insertGetId($info);
			\app\common\System::plog('添加'.t('优惠券').$id);
		}
		return json(['status'=>1,'msg'=>'操作成功','url'=>(string)url('index')]);
	}
	//删除
	public function del(){
		$ids = input('post.ids/a');
		Db::name('coupon')->where('aid',aid)->where('bid',bid)->where('id','in',$ids)->delete();
		Db::name('coupon_record')->where('aid',aid)->where('bid',bid)->where('couponid','in',$ids)->delete();
		\app\common\System::plog('删除'.t('优惠券').implode(',',$ids));
		return json(['status'=>1,'msg'=>'删除成功']);
	}

	//领取数据
	public function record(){
		if(request()->isAjax()){
			$page = input('param.page');
			$limit = input('param.limit');
			if(input('param.field') && input('param.order')){
				$order = 'coupon_record.'.input('param.field').' '.input('param.order');
			}else{
				$order = 'coupon_record.id desc';
			}
			$where = [];
			$where[] = ['coupon_record.aid','=',aid];
			if(input('param.bid') == 'all'){
			
			}else{
                if(false){}else{
                    $where[] = ['coupon_record.bid','=',bid];
                }
			}
			if(input('param.id/d')) $where[] = ['coupon_record.couponid','=',input('param.id/d')];
            if(input('param.mid/d')) $where[] = ['coupon_record.mid','=',input('param.mid/d')];
			if(input('param.recordmid')) $where[] = ['coupon_record.mid','=',input('param.recordmid/d')];

			if(input('param.nickname')) $where[] = ['member.nickname','like','%'.input('param.nickname').'%'];
			if(input('param.remark')) $where[] = ['coupon_record.remark','like','%'.input('param.remark').'%'];
			$count = 0 + Db::name('coupon_record')->alias('coupon_record')->join('member member','coupon_record.mid=member.id')->where($where)->count();
			$data = Db::name('coupon_record')->alias('coupon_record')->field('coupon_record.*,member.nickname,member.headimg')->join('member member','coupon_record.mid=member.id')->where($where)->page($page,$limit)->order($order)->select()->toArray();
			return json(['code'=>0,'msg'=>'查询成功','count'=>$count,'data'=>$data]);
		}
		$coupon = [];
		if(input('param.id/d')){
			$coupon = Db::name('coupon')->where('id',input('param.id/d'))->find();
		}
		View::assign('coupon',$coupon);
		return View::fetch();
	}
	//领取数据导出
	public function recordexcel(){
		if(input('param.field') && input('param.order')){
			$order = 'coupon_record.'.input('param.field').' '.input('param.order');
		}else{
			$order = 'coupon_record.id desc';
		}
		$where = [];
		$where[] = ['coupon_record.aid','=',aid];
		$where[] = ['coupon_record.bid','=',bid];
		$where[] = ['coupon_record.couponid','=',input('param.couponid/d')];
		if(input('param.recordmid')) $where[] = ['coupon_record.mid','=',input('param.recordmid/d')];
		if(input('param.nickname')) $where[] = ['member.nickname','like','%'.input('param.nickname').'%'];
		if(input('param.remark')) $where[] = ['coupon_record.remark','like','%'.input('param.remark').'%'];
		$list = Db::name('coupon_record')->alias('coupon_record')->field('coupon_record.*,member.nickname,member.headimg')->join('member member','coupon_record.mid=member.id')->where($where)->order($order)->select()->toArray();
		
		$title = array();
		$title[] = '序号';
		$title[] = t('优惠券').'名称';
		$title[] = '领取人昵称';
		$title[] = '领取时间';
		$title[] = '到期时间';
		if($list[0]['type'] == 3)
		    $title[] = '总次数/已使用';
		$title[] = '使用时间';
		$title[] = '状态';
        $title[] = '备注';
		$data = array();
		foreach($list as $v){
			$tdata = array();
			$tdata[] = $v['id'];
			$tdata[] = $v['couponname'];
			$tdata[] = $v['nickname'];
			$tdata[] = date('Y-m-d H:i:s',$v['createtime']);
			$tdata[] = date('Y-m-d H:i:s',$v['endtime']);
			if($list[0]['type'] == 3)
                $tdata[] = $v['limit_count'] . ' / ' . $v['used_count'];
            $tdata[] = ($v['status']==1 ? date('Y-m-d H:i:s',$v['usetime']) : '');
			$status = '';
			if($v['status']==0){
				if($v['endtime'] < time()){
					$status = '已过期';
				}else{
					$status = '未使用';
				}
			}elseif($v['status']==1){
				$status = '已使用';
			}
			$tdata[] = $status;
            $tdata[] = $v['remark'];
			$data[] = $tdata;
		}
		$this->export_excel($title,$data);
	}
	//改状态
	public function recordsetst(){
		$ids = input('post.ids/a');
		$st = input('post.st/d');//0未使用，1已使用
		$rlist = Db::name('coupon_record')->where('aid',aid)->where('bid',bid)->where('id','in',$ids)->select()->toArray();
		foreach($rlist as $k=>$v){
			if($v['type']==3){
				return json(['status'=>0,'msg'=>'计次券不能修改状态']);
			}
			Db::name('coupon_record')->where('aid',aid)->where('bid',bid)->where('id',$v['id'])->update(['status'=>$st,'usetime'=>time()]);
			\app\common\Wechat::updatemembercard(aid,$v['mid']);
            if($st == 1){
                \app\common\Coupon::useCoupon(aid,$v['id'],'hexiao');
            }
		}
		\app\common\System::plog('修改'.t('优惠券').'领取记录状态'.implode(',',$ids));
		return json(['status'=>1,'msg'=>'操作成功']);
	}
	//计次券减一次
	public function decCouponOne(){
		$rid = input('post.id/d');
		$cInfo = Db::name('coupon_record')->where('aid',aid)->where('bid',bid)->where('id',$rid)->where('type',3)->where('status',0)->find();
		if (!$cInfo) {
			return json(['status'=>0,'msg'=>'没有找到次券信息']);
		}
		if ($cInfo['used_count'] >= $cInfo['limit_count']) {
			return json(['status'=>0,'msg'=>'已使用全部次数']);
		}
		Db::name('coupon_record')->where('aid',aid)->where('bid',bid)->where('id',$rid)->inc('used_count')->update();
		$data['aid'] = $cInfo['aid'];
		$data['bid'] = bid;
		$data['uid'] = $this->uid;
		$data['mid'] = $cInfo['mid'];
		$data['orderid'] = $cInfo['id'];
		$data['ordernum'] = date('YmdHis');
		$data['title'] = $cInfo['couponname'];
		$data['type'] = 'coupon';
		$data['createtime'] = time();
		$user = Db::name('admin_user')->where('id',$this->uid)->find();
		$data['remark'] = '管理员['.$user['un'].']核销';
		$data['mdid']   = empty($this->user['mdid'])?0:$this->user['mdid'];
		Db::name('hexiao_order')->insert($data);
		if($cInfo['used_count']+1>=$cInfo['limit_count']){
			Db::name('coupon_record')->where('id',$rid)->update(['status'=>1,'usetime'=>time()]);
			\app\common\Wechat::updatemembercard(aid,$cInfo['mid']);
		}
		\app\common\System::plog('计次券减一次'.$rid);

		// 发送消息模板
        return json(['status'=>1,'msg'=>'核销成功']);
	}
	//核销记录
	public function hexiaorecord(){
		$orderid = input('param.crid/d');
		if(request()->isAjax()){
			$page = input('param.page');
			$limit = input('param.limit');
			if(input('param.field') && input('param.order')){
				$order = input('param.field').' '.input('param.order');
			}else{
				$order = 'id desc';
			}
			$where = [];
			$where[] = ['aid','=',aid];
			$where[] = ['bid','=',bid];
			$where[] = ['orderid','=',$orderid];
			$where[] = ['type','=','coupon'];
			$count = Db::name('hexiao_order')->where($where)->count();
			$data = Db::name('hexiao_order')->where($where)->page($page,$limit)->order($order)->select()->toArray();
			if(!$data) $data = [];
			return json(['code'=>0,'msg'=>'查询成功','count'=>$count,'data'=>$data]);
		}
		return View::fetch();
	}
	//删除
	public function recorddel(){
		$ids = input('post.ids/a');
		Db::name('coupon_record')->where('aid',aid)->where('bid',bid)->where('id','in',$ids)->delete();
		\app\common\System::plog('删除'.t('优惠券').'领取记录'.implode(',',$ids));
		return json(['status'=>1,'msg'=>'删除成功']);
	}
    public function delay(){
        }
	//发送优惠券
	public function sendcp(){
		$cpid = input('param.cpid/d');
		$coupon = Db::name('coupon')->where('aid',aid)->where('bid',bid)->where('id',$cpid)->find();
		if(!$coupon) showmsg(t('优惠券').'不存在');

        $default_cid = Db::name('member_level_category')->where('aid',aid)->where('isdefault', 1)->value('id');
        $default_cid = $default_cid ? $default_cid : 0;
        $levelList = Db::name('member_level')->where('aid',aid)->where('cid', $default_cid)->select()->toArray();
		$levelArr = array();
		foreach($levelList as $v){
			$levelArr[$v['id']] = $v['name']; 
		}

		View::assign('coupon',$coupon);
		View::assign('levelArr',$levelArr);
		return View::fetch();
	}
	//发送
	public function send(){
		$page = input('param.pagenum');
		$limit = input('param.pagelimit');
		$persendnum = input('param.persendnum/d');
		if(!$persendnum || $persendnum <=0) return json(['status'=>0,'msg'=>'请输入正确的发送数量']);
		$datawhere = input('post.datawhere/a');
		if($datawhere['field'] && $datawhere['order']){
			$order = $datawhere['field'].' '.$datawhere['order'];
		}else{
			$order = 'id desc';
		}
		if(input('post.sendtype') == "0"){
            if(false){}else{
                $where = "id in(".implode(',', $_POST['ids']).")";
            }
		}elseif(input('post.sendtype') == '1'){
            if(false){}else{
                $where = array();
                $where[] = ['aid','=',aid];
                if($datawhere['pid']) $where[] = ['pid','=',$datawhere['pid']];
                if($datawhere['nickname']) $where[] = ['nickname','like','%'.$datawhere['nickname'].'%'];
                if($datawhere['realname']) $where[] = ['realname','like','%'.$datawhere['realname'].'%'];
                if($datawhere['levelid']) $where[] = ['levelid','=',$datawhere['levelid']];
                if($datawhere['ctime']){
                    $ctime = explode(' ~ ',$datawhere['ctime']);
                    $where[] = ['createtime','>=',strtotime($ctime[0])];
                    $where[] = ['createtime','<',strtotime($ctime[1]) + 86400];
                }
            }
		}else{
			return json(['status'=>0,'msg'=>'参数错误']);
		}
		$cpid = input('post.cpid');
        if(false){}else{
            $datalist = Db::name('member')->where($where)->page($page,$limit)->order($order)->select()->toArray();
        }

		$sucnum = 0;
		$errnum = 0;
		foreach($datalist as $k=>$member){
			for($i=0;$i<$persendnum;$i++){
				$rs = \app\common\Coupon::send(aid,$member['id'],$cpid);
				//dump($rs);exit;
				if($rs['status']==0){
					$errnum++;
				}else{
					$sucnum++;
				}
			}
            }
		\app\common\System::plog('发送'.t('优惠券').$cpid);
		if($sucnum==0){
            return json(['status'=>0,'msg'=>$rs['msg'],'errnum'=>$errnum,'url'=>(string)url('Coupon/record',['id'=>$cpid])]);
        }
		return json(['status'=>1,'msg'=>'发送完成','sucnum'=>$sucnum,'url'=>(string)url('Coupon/record',['id'=>$cpid])]);
	}

	public function choosecoupon(){
		if(request()->isPost()){
			$id = input('param.id/d');
            $where = [];
            $where[] = ['aid','=',aid];
            $where[] = ['id','=',$id];
            if(false){}else{
                $where[] = ['bid', '=', bid];
            }
			$coupon = Db::name('coupon')->where($where)->find();
			return json(['status'=>1,'data'=>$coupon]);
		}
		$type = input('param.type');
        View::assign('type',$type);
        View::assign('module',input('param.module',''));//来源模块
		return View::fetch();
	}

    //复制
    public function copy(){
        $info = Db::name('coupon')->where('aid',aid)->where('bid',bid)->where('id',input('post.id/d'))->find();
        if(!$info) return json(['status'=>0,'msg'=>t('优惠券').'不存在,请重新选择']);
        $data = $info;
        $data['createtime'] = time();
        $data['name'] = '复制-'.$data['name'];
        unset($data['id']);
        $data['getnum'] = 0;

        $newproid = Db::name('coupon')->insertGetId($data);

        \app\common\System::plog(t('优惠券').'复制'.$newproid);
        return json(['status'=>1,'msg'=>'复制成功','objid'=>$newproid]);
    }

	public function creategiveqr(){
		set_time_limit(0);
		ini_set('memory_limit', '2000M');

		if(input('param.field') && input('param.order')){
			$order = 'coupon_record.'.input('param.field').' '.input('param.order');
		}else{
			$order = 'coupon_record.id desc';
		}
		$where = [];
		$where[] = ['coupon_record.aid','=',aid];
		$where[] = ['coupon_record.bid','=',bid];
		$where[] = ['coupon_record.couponid','=',input('param.couponid/d')];
		if(input('param.recordmid')) $where[] = ['coupon_record.mid','=',input('param.recordmid/d')];
		if(input('param.nickname')) $where[] = ['member.nickname','like','%'.input('param.nickname').'%'];
		$list = Db::name('coupon_record')->alias('coupon_record')->field('coupon_record.*,member.nickname,member.headimg')->join('member member','coupon_record.mid=member.id')->where($where)->order($order)->select()->toArray();
		
		$dir = 'upload/temp/'.date('Ym').'/'.date('d_His').rand(1000,9999);
		if(!is_dir(ROOT_PATH.$dir)) mk_dir(ROOT_PATH.$dir);
		$zippath = ROOT_PATH.$dir.'.zip';

		foreach($list as $record){
			$page = 'pagesExt/coupon/coupondetail?id='.$record['couponid'].'&pid='.$record['mid'].'&rid='.$record['id'];
            $errmsg = \app\common\Wechat::getQRCode(aid,'wx',$page,[],bid,false);
            $res = $errmsg['buffer'];//图片 Buffer
            if($errmsg['status'] != 1){
                if($errmsg['errcode'] == 41030){
                    return json(array('status'=>0,'msg'=>'小程序发布后才能生成分享海报'));
                }else{
                    return json(['status'=>0,'msg'=>$errmsg['msg'],'rs'=>$errmsg['rs'],'data'=>$errmsg]);
                }
			}

			file_put_contents(ROOT_PATH.$dir.'/'.$record['id'].'.jpg',$res);
		}
		$myfile = fopen($zippath, "w");
		fclose($myfile);
		\app\common\File::add_file_to_zip(ROOT_PATH.$dir,$zippath,uniqid());
		\app\common\File::remove_dir(ROOT_PATH.$dir);
		$url = PRE_URL.'/'.$dir.'.zip';
		return json(['status'=>1,'msg'=>'打包成功','url'=>$url]);
	}

	public function creategiveqr2(){
		if(input('param.field') && input('param.order')){
			$order = 'coupon_record.'.input('param.field').' '.input('param.order');
		}else{
			$order = 'coupon_record.id';
		}
		$where = [];
		$where[] = ['coupon_record.aid','=',aid];
		$where[] = ['coupon_record.bid','=',bid];
		$where[] = ['coupon_record.couponid','=',input('param.couponid/d')];
		$where[] = Db::raw('from_mid is null');
		if(input('param.recordmid')) $where[] = ['coupon_record.mid','=',input('param.recordmid/d')];
		if(input('param.nickname')) $where[] = ['member.nickname','like','%'.input('param.nickname').'%'];
		$record = Db::name('coupon_record')->alias('coupon_record')->field('coupon_record.*,member.nickname,member.headimg')->join('member member','coupon_record.mid=member.id')->where($where)->order($order)->find();

		if(!$record) return json(['status'=>0,'msg'=>'未找到可转赠的记录']);

		$page = 'pagesExt/coupon/coupondetail?id='.$record['couponid'].'&pid='.$record['mid'].'&rid=all'.$record['id'];
		$rs = \app\common\Wechat::getQRCode(aid,'wx',$page);
		$rs['page'] = $page;
		return json($rs);
	}
    public function set(){
        if(request()->isPost()){
            $info = input('post.info/a');
            $info['aid'] = aid;
            $info['bid'] = bid;
            $info['expire_rules'] = implode(',',$info['expire_rules']);
            Db::name('coupon_set')->where('aid',aid)->where('bid',bid)->update($info);
            \app\common\System::plog(t('优惠券').'设置');
            return json(['status'=>1,'msg'=>'保存成功','url'=>true]);
        }
        $info = Db::name('coupon_set')->where('aid',aid)->where('bid',bid)->find();
        $info['expire_rules'] = explode(',',$info['expire_rules']);
        View::assign('info',$info);
        return View::fetch();
    }
    public function sendNotice(){
        \app\common\Coupon::auto_expire_notice();
    }
}