(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/dp-notice/dp-notice"],{"2a34":function(t,n,e){"use strict";var i=e("65bf"),a=e.n(i);a.a},3455:function(t,n,e){"use strict";var i;e.d(n,"b",(function(){return a})),e.d(n,"c",(function(){return r})),e.d(n,"a",(function(){return i}));var a=function(){var t=this,n=t.$createElement;t._self._c},r=[]},"3c42":function(t,n,e){"use strict";e.r(n);var i=e("3455"),a=e("778d");for(var r in a)"default"!==r&&function(t){e.d(n,t,(function(){return a[t]}))}(r);e("2a34");var u,c=e("f0c5"),o=Object(c["a"])(a["default"],i["b"],i["c"],!1,null,null,null,!1,i["a"],u);n["default"]=o.exports},"3ed5":function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var i=a(e("a34a"));function a(t){return t&&t.__esModule?t:{default:t}}function r(t,n,e,i,a,r,u){try{var c=t[r](u),o=c.value}catch(d){return void e(d)}c.done?n(o):Promise.resolve(o).then(i,a)}function u(t){return function(){var n=this,e=arguments;return new Promise((function(i,a){var u=t.apply(n,e);function c(t){r(u,i,a,c,o,"next",t)}function o(t){r(u,i,a,c,o,"throw",t)}c(void 0)}))}}var c={props:{params:{},data:{}},data:function(){return{animationDuration:"0",animationPlayState:"paused",paddingLift:"0",textAlign:"left"}},mounted:function(){this.data&&1==this.data.length&&this.init()},methods:{init:function(){var t=this;return u(i.default.mark((function n(){var e,a,r;return i.default.wrap((function(n){while(1)switch(n.prev=n.next){case 0:return e=t,a=0,r=0,n.next=4,e.clientWidth(".dp-notice-content");case 4:return a=n.sent.width,n.next=7,e.clientWidth(".dp-content-text");case 7:if(r=n.sent.width,!(r<=a)){n.next=10;break}return n.abrupt("return");case 10:e.paddingLift="100%",e.textAlign="right",e.$nextTick((function(){e.animationAdd()}));case 13:case"end":return n.stop()}}),n)})))()},animationAdd:function(){var t=this;return u(i.default.mark((function n(){var e,a;return i.default.wrap((function(n){while(1)switch(n.prev=n.next){case 0:return e=t,0,a=0,n.next=4,e.clientWidth(".dp-notice-content");case 4:return n.sent.width,n.next=7,e.clientWidth(".dp-content-text");case 7:a=n.sent.width,e.animationDuration="".concat(a/40,"s"),e.animationPlayState="paused",setTimeout((function(){e.animationPlayState="running"}),100);case 11:case"end":return n.stop()}}),n)})))()},clientWidth:function(n){var e=this;return new Promise((function(i){t.createSelectorQuery().in(e).select(n).boundingClientRect((function(t){i(t)})).exec()}))}}};n.default=c}).call(this,e("f266")["default"])},"65bf":function(t,n,e){},"778d":function(t,n,e){"use strict";e.r(n);var i=e("3ed5"),a=e.n(i);for(var r in i)"default"!==r&&function(t){e.d(n,t,(function(){return i[t]}))}(r);n["default"]=a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/dp-notice/dp-notice-create-component',
    {
        'components/dp-notice/dp-notice-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('f266')['createComponent'](__webpack_require__("3c42"))
        })
    },
    [['components/dp-notice/dp-notice-create-component']]
]);
